# Generated by Django 5.2.2 on 2025-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='genre_book',
            field=models.CharField(choices=[('Roman', 'Roman'), ('Fantasy', 'Fantasy'), ('Detective', 'Detective')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=2, upload_to='book/', verbose_name='Загрузите картинку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Напишите автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Дайте описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Напишите название книги'),
        ),
    ]
