# Generated by Django 5.2.2 on 2025-06-16 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('card_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16)], verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('confirmed', 'Подтвержден'), ('not_confirmed', 'Не подтвержден')], default='not_confirmed', max_length=20, verbose_name='Статус')),
                ('books', models.ManyToManyField(to='books.book', verbose_name='Книги')),
            ],
        ),
    ]
