# Generated by Django 5.2.2 on 2025-06-26 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='card_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinLengthValidator(10)], verbose_name='Номер карты'),
        ),
    ]
