# Generated by Django 5.2.2 on 2025-06-26 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basket_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Номер карты'),
        ),
    ]
